database:
  host: db
  port: 5432
  user: postgres
  password: 12345
  name: gomonitor

collector:
  intervalSeconds: 20

#Here are the servers that we will monitor (Testing stand)
servers:
   - name: backend-server1
     address: localhost:8080/users
     description: Server back-end with users
   - name: backend-server2
     address: localhost:8060
     description: Test server